---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
    - name: Install necessary software
      apt:
        name:
          - nginx
          - python3
        state: present
    - name: Start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
    # Security tasks
    - name: Set permissions on /etc/passwd
      file:
        path: /etc/passwd
        owner: root
        group: root
        mode: '0644'
    - name: Disable unused filesystems
      mount:
        name: none
        src: none
        fstype: cramfs
        opts: defaults
        state: absent
    - name: Set password policy
      lineinfile:
        path: /etc/pam.d/common-password
        regexp: '^password\s+requisite\s+pam_pwquality\.so'
        line: 'password requisite pam_pwquality.so retry=3 minlen=12 difok=3 ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1 enforce_for_root'
        state: present
